"""zia tutor integration

Revision ID: 861dde9802fd
Revises: 9ce9d2c6ddd1
Create Date: 2026-09-03 12:46:45.666102
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '861dde9802fd'
down_revision: Union[str, None] = '9ce9d2c6ddd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_curriculum_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_code', sa.String(length=16), nullable=False),
    sa.Column('concept_tag', sa.String(length=96), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('lesson_slug', sa.String(length=160), nullable=True),
    sa.Column('lesson_title', sa.String(length=240), nullable=True),
    sa.Column('lesson_section', sa.String(length=240), nullable=True),
    sa.Column('lesson_url', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_code', 'concept_tag', name='uq_concept_map_track_tag')
    )
    with op.batch_alter_table('concept_curriculum_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_curriculum_map_concept_tag'), ['concept_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_curriculum_map_track_code'), ['track_code'], unique=False)

    op.create_table('zia_learner_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zia_identity', sa.String(length=255), nullable=False),
    sa.Column('zia_session_handle', sa.String(length=255), nullable=True),
    sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_zia_link_user')
    )
    with op.batch_alter_table('zia_learner_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zia_learner_links_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('zia_learner_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zia_learner_links_user_id'))

    op.drop_table('zia_learner_links')
    with op.batch_alter_table('concept_curriculum_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_curriculum_map_track_code'))
        batch_op.drop_index(batch_op.f('ix_concept_curriculum_map_concept_tag'))

    op.drop_table('concept_curriculum_map')
    # ### end Alembic commands ###
