"""scenario attempt content version

Revision ID: acaf1bf56c8b
Revises: 28a6724ba01a
Create Date: 2026-09-20 14:55:48.606359
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acaf1bf56c8b'
down_revision: Union[str, None] = '28a6724ba01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_content_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_attempts', schema=None) as batch_op:
        batch_op.drop_column('scenario_content_version')

    # ### end Alembic commands ###
