"""Request and response models for the AI explanation engine."""

from __future__ import annotations

from pydantic import BaseModel, Field


class ExplanationRequest(BaseModel):
    # Defaults to every incorrectly answered item in the attempt. Narrowing to a single
    # question_id is what the review screen uses when a candidate expands one item, so a
    # 60-item attempt does not fan out twenty generations to render one panel.
    question_ids: list[int] | None = None
    # Ignores the dedup cache and regenerates. Intended for content authors reviewing
    # explanation quality, not for candidates.
    force_regenerate: bool = False


class ExplanationOut(BaseModel):
    question_id: int
    external_id: str
    domain_code: str

    # "ai"     - generated by Claude, or reused from a previous identical mistake
    # "static" - the authored fallback, because AI is unconfigured or the call failed
    source: str
    # True when this exact (question, wrong answer) pair was already cached, so the
    # engine is not billing a fresh generation for every candidate who repeats a mistake.
    reused: bool = False

    why_correct: str = ""
    why_your_answer_wrong: str = ""
    key_concept: str = ""
    blueprint_link: str = ""
    study_tip: str = ""

    # Always populated regardless of source, so the review screen has something to show
    # even when every AI field is empty.
    static_explanation: str = ""

    # Empty unless generation failed. Surfaced so an operator can see why the platform
    # fell back, without the candidate ever seeing an error state.
    detail: str = ""


class ExplanationResponse(BaseModel):
    attempt_id: int
    # Mirrors /health. Lets the frontend label the panel honestly rather than implying
    # Claude wrote text that was actually authored by hand.
    ai_enabled: bool

    generated: int = Field(default=0, description="Fresh Claude API calls made.")
    reused: int = Field(default=0, description="Served from the dedup cache.")
    fell_back: int = Field(default=0, description="Served the authored explanation.")

    explanations: list[ExplanationOut] = Field(default_factory=list)
